/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jEmu816.swgui;

import jEmu816.Util;
import jEmu816.cpu.Cpu;


import javax.swing.*;

/**
 *
 * @author rebecca
 */
public class RegisterPanel extends javax.swing.JPanel {
		private Cpu cpu;

//    GuiController guiController = null;
//    public void setGuiController(GuiController gc) { this.guiController = gc; }
                
    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }

		public void setCpu(Cpu cpu) {
			this.cpu = cpu;
		}

		public void updateRegistersFromCpu() {
			pbrTextField.setText("$" + Util.toHex(cpu.pbr, 2));
			pcTextField.setText("$" + Util.toHex(cpu.pc, 4));
			spTextField.setText("$" + Util.toHex(cpu.sp, 4));
			dbTextField.setText("$" + Util.toHex(cpu.dbr, 2));
			dpTextField.setText("$" + Util.toHex(cpu.dp, 4));
			flagsTextField.setText(cpu.f.toString());
			aRegisterTextField.setText("$" + Util.toHex(cpu.a.getValue(), 4));
			xRegisterTextField.setText("$" + Util.toHex(cpu.x.getValue(), 4));
			yRegisterTextField.setText("$" + Util.toHex(cpu.y.getValue(), 4));
		}

		private int getValueFromEditedRegister(JTextField tf, int digits) {
			String newValue = tf.getText();
			int value = newValue.startsWith("$") ? Integer.parseInt(newValue.substring(1), 16) :	Integer.parseInt(newValue);
			tf.setText("$" + Util.toHex(value, digits));
			return value;
		}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pbrTextField = new javax.swing.JTextField();
        pcTextField = new javax.swing.JTextField();
        spTextField = new javax.swing.JTextField();
        dbTextField = new javax.swing.JTextField();
        dpTextField = new javax.swing.JTextField();
        flagsTextField = new javax.swing.JTextField();
        aRegisterTextField = new javax.swing.JTextField();
        xRegisterTextField = new javax.swing.JTextField();
        yRegisterTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PBR");

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PC");

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SP");

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DB");

        jLabel5.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DP");

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Flags");

        jLabel7.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");

        jLabel8.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("A");

        jLabel9.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Y");

        pbrTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        pbrTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pbrTextField.setText("$XX");
        pbrTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbrTextFieldActionPerformed(evt);
            }
        });

        pcTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        pcTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pcTextField.setText("$XXXX");
        pcTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcTextFieldActionPerformed(evt);
            }
        });

        spTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        spTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spTextField.setText("$XXXX");
        spTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spTextFieldActionPerformed(evt);
            }
        });

        dbTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        dbTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dbTextField.setText("$XX");
        dbTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbTextFieldActionPerformed(evt);
            }
        });

        dpTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        dpTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dpTextField.setText("$XXXX");
        dpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpTextFieldActionPerformed(evt);
            }
        });

        flagsTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        flagsTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        flagsTextField.setText("NVMXDIZC - E");
        flagsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagsTextFieldActionPerformed(evt);
            }
        });

        aRegisterTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        aRegisterTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aRegisterTextField.setText("$XXXX");
        aRegisterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aRegisterTextFieldActionPerformed(evt);
            }
        });

        xRegisterTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        xRegisterTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xRegisterTextField.setText("$XXXX");
        xRegisterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRegisterTextFieldActionPerformed(evt);
            }
        });

        yRegisterTextField.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        yRegisterTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yRegisterTextField.setText("$XXXX");
        yRegisterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yRegisterTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pbrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pcTextField)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aRegisterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xRegisterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yRegisterTextField)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aRegisterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xRegisterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yRegisterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flagsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flagsTextFieldActionPerformed

    private void pbrTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbrTextFieldActionPerformed
			cpu.pbr = getValueFromEditedRegister(pbrTextField, 2);
    }//GEN-LAST:event_pbrTextFieldActionPerformed

    private void dbTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbTextFieldActionPerformed
			cpu.dbr = getValueFromEditedRegister(dbTextField, 2);
    }//GEN-LAST:event_dbTextFieldActionPerformed

    private void xRegisterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRegisterTextFieldActionPerformed
			cpu.x.setValue(getValueFromEditedRegister(xRegisterTextField, 4));
    }//GEN-LAST:event_xRegisterTextFieldActionPerformed

    private void pcTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcTextFieldActionPerformed
			cpu.pc = getValueFromEditedRegister(pcTextField, 4);

			System.out.println("cpu.pc is now set to " + Util.toHex(cpu.pc, 4));

    }//GEN-LAST:event_pcTextFieldActionPerformed

    private void aRegisterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aRegisterTextFieldActionPerformed
			cpu.a.setValue(getValueFromEditedRegister(aRegisterTextField, 4));
    }//GEN-LAST:event_aRegisterTextFieldActionPerformed

    private void yRegisterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yRegisterTextFieldActionPerformed
			cpu.y.setValue(getValueFromEditedRegister(yRegisterTextField, 4));
    }//GEN-LAST:event_yRegisterTextFieldActionPerformed

    private void dpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpTextFieldActionPerformed
			cpu.dp = getValueFromEditedRegister(dpTextField, 4);
    }//GEN-LAST:event_dpTextFieldActionPerformed

    private void spTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spTextFieldActionPerformed
			cpu.sp = getValueFromEditedRegister(spTextField, 4);
    }//GEN-LAST:event_spTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aRegisterTextField;
    private javax.swing.JTextField dbTextField;
    private javax.swing.JTextField dpTextField;
    private javax.swing.JTextField flagsTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pbrTextField;
    private javax.swing.JTextField pcTextField;
    private javax.swing.JTextField spTextField;
    private javax.swing.JTextField xRegisterTextField;
    private javax.swing.JTextField yRegisterTextField;
    // End of variables declaration//GEN-END:variables
}
