/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jEmu816_devices_vera_VeraDevice */

#ifndef _Included_jEmu816_devices_vera_VeraDevice
#define _Included_jEmu816_devices_vera_VeraDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    videoInit
 * Signature: (IFI)Z
 */
JNIEXPORT jboolean JNICALL Java_jEmu816_devices_vera_VeraDevice_videoInit
  (JNIEnv *, jobject, jint, jfloat, jint);

/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    videoReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jEmu816_devices_vera_VeraDevice_videoReset
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    videoEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jEmu816_devices_vera_VeraDevice_videoEnd
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    videoRead
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_jEmu816_devices_vera_VeraDevice_videoRead
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    videoWrite
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_jEmu816_devices_vera_VeraDevice_videoWrite
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    videoStep
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jEmu816_devices_vera_VeraDevice_videoStep
  (JNIEnv *, jobject, jint);

/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    videoUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jEmu816_devices_vera_VeraDevice_videoUpdate
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    getSDLEvent
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jEmu816_devices_vera_VeraDevice_getSDLEvent
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_devices_vera_VeraDevice
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jEmu816_devices_vera_VeraDevice_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
