/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jEmu816_Main */

#ifndef _Included_jEmu816_Main
#define _Included_jEmu816_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jEmu816_Main
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jEmu816_Main_intMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
