/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jEmu816_Main */

#ifndef _Included_jEmu816_Main
#define _Included_jEmu816_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jEmu816_Main
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jEmu816_Main_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     jEmu816_Main
 * Method:    step
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jEmu816_Main_step
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_Main
 * Method:    loadFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jEmu816_Main_loadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jEmu816_Main
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jEmu816_Main_reset
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_Main
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jEmu816_Main_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
