/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef LIBEMU816_H
#define LIBEMU816_H

#ifdef _WIN32
#define LIBEMU816_EXPORT_FUNC __declspec(dllexport)
#else
#define LIBEMU816_EXPORT_FUNC
#endif

#include <string>

namespace libEmu816 {
    class Greeter {
        public:
        std::string LIBEMU816_EXPORT_FUNC greeting();
    };
}

#endif
