/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jEmu816_NativeWrapper */

#ifndef _Included_jEmu816_NativeWrapper
#define _Included_jEmu816_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jEmu816_NativeWrapper
 * Method:    isStopped
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jEmu816_NativeWrapper_isStopped
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_NativeWrapper
 * Method:    step
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jEmu816_NativeWrapper_step
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_NativeWrapper
 * Method:    getStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jEmu816_NativeWrapper_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_NativeWrapper
 * Method:    loadFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jEmu816_NativeWrapper_loadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jEmu816_NativeWrapper
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jEmu816_NativeWrapper_reset
  (JNIEnv *, jobject);

/*
 * Class:     jEmu816_NativeWrapper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jEmu816_NativeWrapper_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
